In [1]:
import tensorflow as tf

In [2]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [1]:
import tensorflow as tf

X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)

for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [2]:
dataset = tf.data.Dataset.from_tensor_slices(X).repeat(3).batch(7, drop_remainder= True)

for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [4]:
dataset = dataset.map(lambda x : x ** 2, num_parallel_calls= 5)

for item in dataset:
    print(item)

tf.Tensor([   0    1   16   81  256  625 1296], shape=(7,), dtype=int32)
tf.Tensor([2401 4096 6561    0    1   16   81], shape=(7,), dtype=int32)
tf.Tensor([ 256  625 1296 2401 4096 6561    0], shape=(7,), dtype=int32)
tf.Tensor([   1   16   81  256  625 1296 2401], shape=(7,), dtype=int32)


In [ ]:
dataset = dataset.apply(tf.data.experimental.unbatch()) # unbatch method has been deprecated
dataset = dataset.filter(lambda x : x > 5)
for item in dataset.take(4):
    print(item)

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(256, shape=(), dtype=int32)
tf.Tensor(625, shape=(), dtype=int32)


In [14]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.shuffle(buffer_size= 5, seed= 42, reshuffle_each_iteration= False).batch(7, drop_remainder= True).repeat(3)

for item in dataset:
    print(item)

tf.Tensor([2 5 1 7 0 8 6], shape=(7,), dtype=int64)
tf.Tensor([2 5 1 7 0 8 6], shape=(7,), dtype=int64)
tf.Tensor([2 5 1 7 0 8 6], shape=(7,), dtype=int64)


In [15]:
X_mean, X_std = [1, 2] , [1, 1] # mean, standard deviation of 2 features dataset
n_inputs = 2

def preprocess(line):
    defs = [0.] * n_inputs + [tf.constant([], dtype= tf.float32)]
    fields = tf.io.decode_csv(line, record_defaults= defs)
    X = fields.stack[:-1]
    y = fields.stack[-1:]
    return (X - X_mean)/X_std, y
