In [12]:
import tensorflow as tf
from tensorflow.train import BytesList, FloatList, Int64List
from tensorflow.train import Feature, Features, Example

In [13]:
person_example = Example(features= Features(
    feature = {
        "name" : Feature(bytes_list= BytesList(value= [b"Nathan Solomon"])),
        "id" : Feature(int64_list= Int64List(value= [1])),
        "email" : Feature(bytes_list= BytesList(value= [b"nathansolomon@std.iyte.edu.tr", b"solomonnathanmekuria@gmail.com"]))
    }
))

In [14]:
# serialize person_example and write it in TFRecord
with tf.io.TFRecordWriter("my_contacts.tfrecord") as f:
    f.write(person_example.SerializeToString())

In [ ]:
# parse the serialized data
feature_description = {
    "name" : tf.io.FixedLenFeature([], tf.string, default_value= ""),
    "id" : tf.io.FixedLenFeature([], tf.int64, default_value= 0),
    "email" : tf.io.VarLenFeature(tf.string)
}

for serialized_example in tf.data.TFRecordDataset(["my_contacts.tfrecord"]):
    parse_example = tf.io.parse_single_example(serialized_example, feature_description)
    print(parse_example)

{'email': SparseTensor(indices=tf.Tensor(
[[0]
 [1]], shape=(2, 1), dtype=int64), values=tf.Tensor([b'nathansolomon@std.iyte.edu.tr' b'solomonnathanmekuria@gmail.com'], shape=(2,), dtype=string), dense_shape=tf.Tensor([2], shape=(1,), dtype=int64)), 'id': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'name': <tf.Tensor: shape=(), dtype=string, numpy=b'Nathan Solomon'>}
